name: fifth

on:
  push:
    branches:
      [master]

  workflow_dispatch:

jobs:
    build:


        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v2
          - name: Setup java
            uses: actions/setup-java@v1
            with:
              java-version: '11'
          - name: Test Unitary
            run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test
          - name: Test ApiRest
            run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test
          - name: Test Selenium
            run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' test 
          - name: Upload jar for next job
            uses: actions/upload-artifact@v1
            with:
              name: target
              path: target
              retention-days: '1'

    publish_in_heroku_registry:
        runs-on: ubuntu-20.04
        needs: [build]
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP: ${{ secrets.HEROKU_APP }}
        steps:
          - name: Clone repository
            uses: actions/checkout@v2
          - name: Download Jar from previous job
            uses: actions/download-artifact@v1
            with:
              name: target
          - name: Generate tag
            run: echo ::set-output name=tag::$VERSION=$(mvn -q help:evaluate -Dexpression=project.version-DforceStdout)
            id: project
          - name: Install Heroku CLI
            run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          - name: Login to eroku container resistry
            run: heroku container:login 


    deploy_to_heroku:
      name: Deploy to Heroku
      runs-on: ubuntu-latest
      needs: [publish_in_heroku_registry]
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
      steps:
      
        - name: Install Heroku CLI
          run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        - name: Login in Heroku
          run: heroku container:login
        - name: Deploy in Heroku
          run: heroku container:release web

    smoketest_on_heroku_app:
        name: Execute Smoke Test
        runs-on: ubuntu-20.04
        needs: [deploy_to_heroku]
        steps:
          - name: Clone repository
            uses: actions/checkout@v2
          - name: Test Selenium
            run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' test "-Dhost=https://git.heroku.com/ais-destevezr-sbravoma-2021.git" test
          - name: Test ApiRest
            run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test "-Dhost=https://git.heroku.com/ais-destevezr-sbravoma-2021.git" test            
           