name: first

on:
  push:
    branches:
      [main]

  workflow_dispatch:

jobs:
    build:


        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
        steps:
          - uses: actions/checkout@v2
          - name: Setup java
            uses: actions/setup-java@v1
            with:
              java-version: '11'
          - name: Test Unitary
            run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test
          - name: Test ApiRest
            run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test