name : third
on : 
  push:
        branches:
            [release]
  workflow_dispatch:
 

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:     
        - uses: actions/checkout@v2 
        - name: Setup java
          uses: actions/setup-java@v1
          with:
            java-version: '11'
        - name: Build Native with Maven
          run: mvn -B package -DskipTests
        - name: Upload jar for next job
          uses: actions/upload-artifact@v1
          with:
            name: target
            path: target
            retention-days: '1'
    
    publish_in_dockerhub:
        runs-on: ubuntu-20.04
        needs: [build]
        steps:
          - name: Clone repository
            uses: actions/checkout@v2
          - name: Download Jar from previous job
            uses: actions/download-artifact@v1
            with:
              name: target
          - name: Generate tag
            run: echo ::set-output name=tag::$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)
            id: project
          - name: Login to DockerHub
            run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
          - name: Build image
            run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webapp:${{ steps.project.outputs.tag }} .
          - name: Push image to DockerHub
            run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:${{ steps.project.outputs.tag}}
